#!/bin/bash
# My first script

{ # try
        echo "Started installation"
        cp -rf .vimrc ~/
        cp -rf .vim ~/
        echo "Installation completed"
} || { # catch
        echo "Somthing went wrong"
}
