#!/bin/bash

{ # try
    echo "Started installation"
    echo "Backing up current settings"
    if [ ! -f ~/.bashrc.backup ]; then
        mv ~/.bashrc ~/.bashrc.backup
    fi
    echo "Copying configs"
    cp -rf .vimrc ~/
    cp -rf .vim ~/
    cp -rf .tmux.conf ~/
    cp -rf .tmux_colours* ~/
    cp -rf .gitconfig ~/
    cp -rf .gitmessage ~/
    cp -rf .bash_custom ~/
    cp -rf .bash.d ~/
    cp -rf .local/bin ~/
    echo "Generating default files"
    {
    cat << EOF
if [ -f ~/.bashrc.backup ]; then
    . ~/.bashrc.backup
fi
if [ -f ~/.bash_custom ]; then
    . ~/.bash_custom
fi
EOF
    } >| ~/.bashrc
} || { # Catch
echo "Somthing went wrong"
}
