#!/bin/bash

{ # try
    echo "Started installation"
    echo "Backing up current settings"
    mv ~/.bashrc.backup ~/.bashrc || mv ~/.bashrc ~/.bashrc.backup  # Restore backup first so reinstalls don't overwrite the backup
    mv ~/.bash_profile.backup ~/.bash_profile || mv ~/.bash_profile ~/.bash_profile.backup
    echo "Copying configs"
    cp -rf .vimrc ~/
    cp -rf .vim ~/
    cp -rf .tmux.conf ~/
    cp -rf .tmux_colours* ~/
    cp -rf .gitconfig ~/
    cp -rf .gitmessage ~/
    cp -rf .bash_custom ~/
    cp -rf .bash.d ~/
    echo "Generating default files"
    echo ". ~/.bashrc.backup" >> ~/.bashrc
    echo ". ~/.bash_custom" >> ~/.bashrc
    echo ". ~/.bash_profile.backup" >> ~/.bash_profile
    echo ". ~/.bash_custom" >> ~/.bash_profile
    echo "Installation completed"
} || { # Catch
echo "Somthing went wrong"
}
