
# I *think* alt + <- / -> is supposed to jump by word
# But it doesn't work well, I rarely use that, and it breaks the keybinds for moving between tabs/panes in jellij
# So disable it, to pass onto the underlying program (e.g. multiplexer)
keybind = alt+left=unbind
keybind = alt+right=unbind
